version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - misspell
    - unconvert
    - gocritic

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
